# Generated by Django 5.1.5 on 2025-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0002_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=30)),
                ('original_title', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=4)),
                ('requirement_age', models.IntegerField()),
                ('prod_date', models.CharField(max_length=4)),
                ('prod_country', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=100)),
                ('scenario', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('mounting', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=30)),
                ('fees', models.CharField(max_length=30)),
                ('time', models.TimeField(default='00:00:00')),
                ('film_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='email_date',
            field=models.DateTimeField(verbose_name='date regist'),
        ),
    ]
