# Generated by Django 5.1.5 on 2025-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0003_filmpage_alter_email_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpage',
            name='link_title',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
