# Generated by Django 5.1.6 on 2025-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk_app', '0004_filmpage_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpage',
            name='genre',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
